language: python
sudo: required

python:
  - "2.7"

addons:
  apt:
    packages:
    - libpq-dev
    - python-dev

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python tests/tests.py
  - coverage run python tests/tests.py

after_success: coveralls

notifications:
  slack: lacnic-eng:jSDKPP0pyOgA5JV4lsQTGtuP
